version: '3.7'
services:
  app:
    image: node:20.11.1
    working_dir: /usr/src/app
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
    command: >
      bash -c "npm install &&
      npm install nodemon -g &&
      env-cmd -f ./config/.env.dev nodemon --es-module-specifier-resolution=node src/index.js
