FROM node:20.11.1

RUN apt-get update && apt-get install ffmpeg -y

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3500

CMD [ "npm", "run", "server:dev" ]

# image変わったから、またimage buildせんといかんね。
